---
title: "Lab 2"
author: "Nathaniel Gunter"
date: "1/21/2020"
output: 
  html_document:
      toc: yes
      toc_float: yes
      theme: darkly
      highlights: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lattice)
```
# Lab 2

## Task 1

```{r workingDirectory}
getwd()
```

## Task 2

```{r readTable}
epagas<-read.csv('EPAGAS.csv')
head(epagas)
```

## Task 3

```{r makeMpg}
mpg<-epagas$MPG
z<-(mpg-mean(mpg))/(sd(mpg))
mean(z)
sd(z)
```

Note: 1.058709e-16 is close to working precision such that it is essentially zero.

```{r buildMpgaug}
mpgaug<-data.frame('mpg' = mpg)
mpgaug['zscore']<-z
mpgaug['outlier']<-'NO'
```

```{r possibleOutliers}
mpgaug$outlier[abs(mpgaug$zscore)>=2 & abs(mpgaug$zscore)<=3]<-'POSSIBLE'
mpgaug$mpg[mpgaug$outlier=='POSSIBLE']
```

```{r definedOutliers}
mpgaug$outlier[abs(mpgaug$zscore)>3]<-'YES'
mpgaug$mpg[mpgaug$outlier=='YES']
```

```{r latticeGraph}
mycol<- ifelse(mpgaug$outlier=='YES',"Red", ifelse(mpgaug$outlier=='POSSIBLE',"Blue","Black"))
with(mpgaug,dotplot(~mpg,col=mycol))
```

## Task 4


